[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = true
hideSidebarNav = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[global]
developmentMode = false
logLevel = "error"
showWarningOnDirectExecution = false

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = true

[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"